# Server settings
server:
    tomcat:
        basedir: /var/tmp/oneblog/blog-admin
# SPRING PROFILES
spring:
    profiles:
        include: [center-dev]

# logging settings
logging:
    config: classpath:logback-spring.xml
    file:
      path: /var/tmp/oneblog/blog-admin

####################################自定义配置##########################################
app:
    # 是否启用kaptcha验证码
    enableKaptcha: false
    # 是否启用自动校验友情链接的功能
    # 请选择打开，一旦打开，每晚凌晨12点会自动检查友联，对于不包含本站链接的网站实行自动封禁
    # 目前暂时没实现白名单的功能
    enableAutoCheckLink: true
    # 启用后，项目在启动时会打印数据库（Mysql和Redis）链接信息（包含密码）
    # 代码请参考
    enabledPrintConfig: true
    # shiro配置项
    shiro:
        loginUrl: "/passport/login/"
        successUrl: "/"
        unauthorizedUrl: "/error/403"
    # CDN 域名【"" 获取 http://www.cdn.com】
    cdnDomain: ""
    cdnVersion: "v=1.0.0.0"
####################################自定义配置##########################################
